spring.application.name=boot_01

# DB 설정
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/community?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=${DB_USER_NAME:root}
spring.datasource.password=${DB_PASSWORD:root}

# JPA 설정
# 엔티티 클래스의 변경사항을 감지하여 DB 테이블을 자동으로 업뎃
spring.jpa.hibernate.ddl-auto=update
# SQL문을 콘솔에 출력
spring.jpa.show-sql=true  
# 콘솔에 출력되는 SQL문을 정렬 
spring.jpa.properties.hibernate.format_sql=true
# JPA 사용할 DBMS 종류를 지정
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 32자 이상의 임의 문자열 설정
jwt.secret= ${JWT_SECRET:your-super-secret-key-that-is-at-least-32-bytes-long}
# 1시간 (밀리초)
# jwt.expiration= 3600000
jwt.access-token-in-ms = 60000
# 7일 = 1000(밀리초) * 60(초) * 60(분) * 24(시간) * 7(일)
jwt.refresh-token-in-ms = 604800000